apiVersion: v1
kind: Service
metadata:
  name: frontend-app-service
  namespace: exam-maxmudov
spec:
  type: NodePort
  selector:
    app: frontend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30036
