apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myexam-app
  namespace: exam-maxmudov
  labels:
    name: myexam-app
spec:
  ingressClassName: nginx
  rules:
  - host: amahmudov.nvrbckdown.uz
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: exam-service
            port:
              number: 80
