apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  namespace: exam-maxmudov
  labels:
    project: practice
    author: maxmudov
spec:
  containers:
  - name: nginx2
    image: nginx:latest
    ports:
      - containerPort: 80
