apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  namespace: exam-maxmudov
  labels:
    project: practice
    author: maxmudov
spec:
  containers:
  - name: nginx1
    image: nginx:latest
    ports:
      - containerPort: 80
