apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: myexam
  namespace: exam-maxmudov
  labels:
    app: myexam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myexam
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myexam
    spec:
      containers:
      - image: maxmudovk8s/uacademy:repo-1
        name: myexam
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: info
              key: env

        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: info
              key: log_leveI

        - name: GRPC_PORT
          valueFrom:
            configMapKeyRef:
              name: info
              key: grpc_port

        - name: DB_URI
          valueFrom:
            secretKeyRef:
              name: myexam
              key: DB_URI

        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

        ports:
        - containerPort: 80
