apiVersion: v1
kind: Service
metadata:
  name: exam-service
  namespace: exam-maxmudov
spec:
  type: NodePort
  selector:
    app: myexam-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30043
